const piecesData = [
  {
    name: "white_pawn_1",
    pos: 12,
    type: "pawn",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "white_pawn_2",
    pos: 22,
    type: "pawn",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "white_pawn_3",
    pos: 32,
    type: "pawn",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "white_pawn_4",
    pos: 42,
    type: "pawn",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "white_pawn_5",
    pos: 52,
    type: "pawn",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "white_pawn_6",
    pos: 62,
    type: "pawn",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "white_pawn_7",
    pos: 72,
    type: "pawn",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "white_pawn_8",
    pos: 82,
    type: "pawn",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "white_bishop_1",
    pos: 31,
    type: "bishop",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "white_bishop_2",
    pos: 61,
    type: "bishop",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "white_knight_1",
    pos: 21,
    type: "knight",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "white_knight_2",
    pos: 71,
    type: "knight",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "white_rook_1",
    pos: 11,
    type: "rook",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "white_rook_2",
    pos: 81,
    type: "rook",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "white_king",
    pos: 51,
    type: "king",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "white_queen",
    pos: 41,
    type: "queen",
    eaten: false,
    color: "white",
    moved: false,
  },
  {
    name: "black_pawn_1",
    pos: 17,
    type: "pawn",
    eaten: false,
    color: "black",
    moved: false,
  },
  {
    name: "black_pawn_2",
    pos: 27,
    type: "pawn",
    eaten: false,
    color: "black",
    moved: false,
  },
  {
    name: "black_pawn_3",
    pos: 37,
    type: "pawn",
    eaten: false,
    color: "black",
    moved: false,
  },
  {
    name: "black_pawn_4",
    pos: 47,
    type: "pawn",
    eaten: false,
    color: "black",
    moved: false,
  },
  {
    name: "black_pawn_5",
    pos: 57,
    type: "pawn",
    eaten: false,
    color: "black",
    moved: false,
  },
  {
    name: "black_pawn_6",
    pos: 67,
    type: "pawn",
    eaten: false,
    color: "black",
    moved: false,
  },
  {
    name: "black_pawn_7",
    pos: 77,
    type: "pawn",
    eaten: false,
    color: "black",
    moved: false,
  },
  {
    name: "black_pawn_8",
    pos: 87,
    type: "pawn",
    eaten: false,
    color: "black",
    moved: false,
  },
  {
    name: "black_bishop_1",
    pos: 38,
    type: "bishop",
    eaten: false,
    color: "black",
    moved: false,
  },
  {
    name: "black_bishop_2",
    pos: 68,
    type: "bishop",
    eaten: false,
    color: "black",
    moved: false,
  },
  {
    name: "black_knight_1",
    pos: 28,
    type: "knight",
    eaten: false,
    color: "black",
    moved: false,
  },
  {
    name: "black_knight_2",
    pos: 78,
    type: "knight",
    eaten: false,
    color: "black",
    moved: false,
  },
  {
    name: "black_rook_1",
    pos: 18,
    type: "rook",
    eaten: false,
    color: "black",
    moved: false,
  },
  {
    name: "black_rook_2",
    pos: 88,
    type: "rook",
    eaten: false,
    color: "black",
    moved: false,
  },
  {
    name: "black_king",
    pos: 58,
    type: "king",
    eaten: false,
    color: "black",
    moved: false,
  },
  {
    name: "black_queen",
    pos: 48,
    type: "queen",
    eaten: false,
    color: "black",
    moved: false,
  },
];

export default piecesData;
