const piecesData = [
  {
    name: "white_pawn_1",
    pos: "a_2",
    type: "pawn",
    eaten: false,
    color: "white",
  },
  {
    name: "white_pawn_2",
    pos: "b_2",
    type: "pawn",
    eaten: false,
    color: "white",
  },
  {
    name: "white_pawn_3",
    pos: "c_2",
    type: "pawn",
    eaten: false,
    color: "white",
  },
  {
    name: "white_pawn_4",
    pos: "d_2",
    type: "pawn",
    eaten: false,
    color: "white",
  },
  {
    name: "white_pawn_5",
    pos: "e_2",
    type: "pawn",
    eaten: false,
    color: "white",
  },
  {
    name: "white_pawn_6",
    pos: "f_2",
    type: "pawn",
    eaten: false,
    color: "white",
  },
  {
    name: "white_pawn_7",
    pos: "g_2",
    type: "pawn",
    eaten: false,
    color: "white",
  },
  {
    name: "white_pawn_8",
    pos: "h_2",
    type: "pawn",
    eaten: false,
    color: "white",
  },
  {
    name: "white_bishop_1",
    pos: "c_1",
    type: "bishop",
    eaten: false,
    color: "white",
  },
  {
    name: "white_bishop_2",
    pos: "f_1",
    type: "bishop",
    eaten: false,
    color: "white",
  },
  {
    name: "white_knight_1",
    pos: "b_1",
    type: "knight",
    eaten: false,
    color: "white",
  },
  {
    name: "white_knight_2",
    pos: "g_1",
    type: "knight",
    eaten: false,
    color: "white",
  },
  {
    name: "white_rook_1",
    pos: "a_1",
    type: "rook",
    eaten: false,
    color: "white",
  },
  {
    name: "white_rook_2",
    pos: "h_1",
    type: "rook",
    eaten: false,
    color: "white",
  },
  {
    name: "white_king",
    pos: "e_1",
    type: "king",
    eaten: false,
    color: "white",
  },
  {
    name: "white_queen",
    pos: "d_1",
    type: "queen",
    eaten: false,
    color: "white",
  },
  {
    name: "black_pawn_1",
    pos: "a_7",
    type: "pawn",
    eaten: false,
    color: "black",
  },
  {
    name: "black_pawn_2",
    pos: "b_7",
    type: "pawn",
    eaten: false,
    color: "black",
  },
  {
    name: "black_pawn_3",
    pos: "c_7",
    type: "pawn",
    eaten: false,
    color: "black",
  },
  {
    name: "black_pawn_4",
    pos: "d_7",
    type: "pawn",
    eaten: false,
    color: "black",
  },
  {
    name: "black_pawn_5",
    pos: "e_7",
    type: "pawn",
    eaten: false,
    color: "black",
  },
  {
    name: "black_pawn_6",
    pos: "f_7",
    type: "pawn",
    eaten: false,
    color: "black",
  },
  {
    name: "black_pawn_7",
    pos: "g_7",
    type: "pawn",
    eaten: false,
    color: "black",
  },
  {
    name: "black_pawn_8",
    pos: "h_7",
    type: "pawn",
    eaten: false,
    color: "black",
  },
  {
    name: "black_bishop_1",
    pos: "c_8",
    type: "bishop",
    eaten: false,
    color: "black",
  },
  {
    name: "black_bishop_2",
    pos: "f_8",
    type: "bishop",
    eaten: false,
    color: "black",
  },
  {
    name: "black_knight_1",
    pos: "b_8",
    type: "knight",
    eaten: false,
    color: "black",
  },
  {
    name: "black_knight_2",
    pos: "g_8",
    type: "knight",
    eaten: false,
    color: "black",
  },
  {
    name: "black_rook_1",
    pos: "a_8",
    type: "rook",
    eaten: false,
    color: "black",
  },
  {
    name: "black_rook_2",
    pos: "h_8",
    type: "rook",
    eaten: false,
    color: "black",
  },
  {
    name: "black_king",
    pos: "e_8",
    type: "king",
    eaten: false,
    color: "black",
  },
  {
    name: "black_queen",
    pos: "d_8",
    type: "queen",
    eaten: false,
    color: "black",
  },
];

export default piecesData;
